Fix typo
d2l-ai/d2l-en pull request #1447
Opened 2020-09-16 13:54 UTC by phupe

*Description of changes:*

Minor typos fixed

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2020-09-16 14:03 UTC, mli commented
Job d2l-en/PR-1447/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1447/

2020-09-16 14:23 UTC, phupe commented
check OK on my side on http://preview.d2l.ai/d2l-en/PR-1447/ for the 3 pages modified

2020-09-16 17:58 UTC, AnirudhDagar requested changes

2020-09-16 17:58 UTC, AnirudhDagar commented on chapter_linear-networks/image-classification-dataset.md
> +by 60000 images in the training dataset and by 10000 in the test dataset.
These are already correct since we have 6000 examples for **EACH** class. Please revert these changes.

2020-09-16 19:46 UTC, phupe commented
right, number is per category. change has been reverted.

2020-09-17 05:30 UTC, astonzhang commented
Thanks!

2020-09-17 05:31 UTC, merged