Include difference of net(X) and net.forward(X)
d2l-ai/d2l-en pull request #1623
Opened 2021-01-10 17:28 UTC by floriandonhauser

In pytorch, `net(X)` is shorthand for `net.__call__(X)` which is not exactly the same as `net.forward(X)`.
`net.__call__(X)` also includes hooks which might be necessary for the forward and backward pass.
This book, as far as I understand, does not include any mention of Pytorch's hooks and the reader might think that both calls are identical.
However, `net(X)` is the right way to use the model, since calling `net.forward(X)` directly will not call possibly required hooks.
In my opinion, this difference should be mentioned at some point in the book.
The exact wording can be changed, of course, but some explanation of the difference would be helpful for the reader.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2021-01-10 17:36 UTC, mli commented
Job d2l-en/PR-1623/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1623/

2021-01-11 00:04 UTC, astonzhang commented
Thanks. If you want to update text about PyTorch, do you wish to modify the text following the :begin_tab:`pytorch` ? (This PR so far modifies text following the :begin_tab:`mxnet` )

2021-01-11 08:03 UTC, floriandonhauser commented
Actually, for mxnet, you also have hooks. See: [the source code of Block](https://github.com/apache/incubator-mxnet/blob/124d8417984ed9205f972eb1c2cadbf028b94eb3/python/mxnet/gluon/block.py#L846)
I would suggest both to change both tabs, mxnet and Pytorch.

2021-01-11 08:18 UTC, mli commented
Job d2l-en/PR-1623/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1623/

2021-01-11 08:25 UTC, floriandonhauser commented
For TensorFlow Keras I am a bit unsure what the exact difference is between call() and __call__().
[The sourcecode](https://github.com/tensorflow/tensorflow/blob/287ab9046604c277908969e20b7b4c0febe8b4ab/tensorflow/python/keras/engine/training.py#L465) says
"Note: This method should not be called directly. It is only meant to be
    overridden when subclassing `tf.keras.Model`.
    To call a model on an input, always use the `__call__` method,
    i.e. `model(inputs)`, which relies on the underlying `call` method."
Therefore, this should probably also be included in the book so readers do not use call(X) because they think it is exactly the same.

2021-01-11 19:31 UTC, astonzhang commented
Thanks. @AnirudhDagar Could you review the PyTorch part?

2021-01-11 20:37 UTC, AnirudhDagar requested changes
Overall looks good to me. Thanks for this handy addition. Please make the suggested change.

2021-01-11 20:37 UTC, AnirudhDagar commented on chapter_deep-learning-computation/model-construction.md
> +In general, a Block should be used with `net(X)` and not
```suggestion
In general, a `Block` should be used with `net(X)` and not
```

2021-01-11 20:37 UTC, AnirudhDagar commented on chapter_deep-learning-computation/model-construction.md
> +In general, a Module should be used with `net(X)` and not
```suggestion
In general, a `Module` should be used with `net(X)` and not
```

2021-01-11 20:45 UTC, AnirudhDagar approved these changes

2021-01-11 22:14 UTC, mli commented
Job d2l-en/PR-1623/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1623/

2021-01-11 22:20 UTC, mli commented
Job d2l-en/PR-1623/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1623/

2021-01-12 18:02 UTC, AnirudhDagar commented
@astonzhang LGTM!

2021-01-12 18:48 UTC, astonzhang commented
Thanks. I'll merge and edit the MXNet part

2021-01-12 18:48 UTC, merged

2021-01-12 19:01 UTC, floriandonhauser commented
@astonzhang The MXNet has actually been changed as well. The missing one is TensorFlow for which @terrytangyuan is responsible as far as I know. As I wrote above, a similar difference between `__call__()` and `call()` exists here as well.