Adding no_grad context manager block to the PyTorch versions of `eval…
d2l-ai/d2l-en pull request #1786
Opened 2021-06-11 23:11 UTC by varadgunjal

…uate_accuracy` and `evaluate_accuracy_gpu` functions

As detailed in the PyTorch forums (https://discuss.pytorch.org/t/model-eval-vs-with-torch-no-grad/19615/2), evaluation should use both `net.eval()` and `with torch.no_grad()` since they serve different purposes and there are clear performance benefits to be gotten when using `with torch.no_grad()`. Attaching a notebook with finetuning on the Hot Dog dataset to demonstrate the differences in training speed (please change extension to .ipynb to verify, Github wasn't allowing me to upload a .ipynb file  so converted it to .txt).

[no_grad_expts.txt](https://github.com/d2l-ai/d2l-en/files/6641217/no_grad_expts.txt)

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2021-06-12 01:09 UTC, AnirudhDagar requested changes
Hi @varadgunjal! Yeah as discussed in (#1741, see [comment](https://github.com/d2l-ai/d2l-en/issues/1741#issuecomment-835548527)),  it is definitely a good practice to avoid grad computation during inference. Thanks a lot for the PR :))

Everything LGTM, except that these functions are also saved in the d2l [library](https://github.com/d2l-ai/d2l-en/tree/master/d2l). So it would be great if you can update that. There is no need to manually change the `d2l/torch.py` file. You just need to generate that using `d2lbook build lib` once you have made the changes to the notebook (which you already have). Lemme know if you need some help with this.

The CI seems to be failing for TF and that is totally unrelated to your change. @terrytangyuan @astonzhang any ideas?

2021-06-12 05:34 UTC, mli commented
Job d2l-en/PR-1786/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1786/

2021-06-12 05:36 UTC, astonzhang commented
> Hi @varadgunjal! Yeah as discussed in (#1741, see [comment](https://github.com/d2l-ai/d2l-en/issues/1741#issuecomment-835548527)), it is definitely a good practice to avoid grad computation during inference. Thanks a lot for the PR :))
> 
> Everything LGTM, except that these functions are also saved in the d2l [library](https://github.com/d2l-ai/d2l-en/tree/master/d2l). So it would be great if you can update that. There is no need to manually change the `d2l/torch.py` file. You just need to generate that using `d2lbook build lib` once you have made the changes to the notebook (which you already have). Lemme know if you need some help with this.
> 
> The CI seems to be failing for TF and that is totally unrelated to your change. @terrytangyuan @astonzhang any ideas?

Now the CI passes 
http://ci.d2l.ai/blue/organizations/jenkins/d2l-en/detail/PR-1786/3/pipeline/

2021-06-14 21:28 UTC, varadgunjal commented
Thanks @AnirudhDagar. I had no idea this had already been addressed in a previous issue - I randomly encountered this when teaching the CV technique course for MLU. Regarding the build you have requested, I'm assuming I just run the build command in the git directory on my machine? Does the `d2lbook` command need to be setup somehow? (I haven't done this as yet)

2021-06-15 03:19 UTC, AnirudhDagar commented
@varadgunjal yes you should run the command in your clone of the repo. See my comment [here](https://github.com/d2l-ai/d2l-en/pull/1793#issuecomment-860420518) for installing [d2lbook](https://github.com/d2l-ai/d2l-book).

2021-06-15 19:20 UTC, varadgunjal commented
@AnirudhDagar I installed `d2lbook` from  https://pypi.org/project/d2lbook/ before I saw your comment. Will that work as well or do I need some new changes from the current version in the git repo of `d2lbook`?

Also, after running `d2lbook build lib`, only the following lines are printed - 

`[d2lbook:config.py:L12] INFO   Load configure from config.ini
[d2lbook:build.py:L49] INFO   === Finished "d2lbook build lib_mxnet" in 00:00:02`

and I see no changes to commit. Am I doing something wrong?

2021-06-16 01:41 UTC, AnirudhDagar commented
No @varadgunjal, please use the git repo to install the latest version as suggested in the comment. The PyPi wheels available are more than an year old.

2021-06-16 18:59 UTC, merged

2021-06-16 19:02 UTC, astonzhang commented
Now it's synced at https://github.com/d2l-ai/d2l-en/commit/c91bfde627540f824ef0e28cc49bf6788a265a00

@varadgunjal ,  could you send another PR to replace your id with name in our acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md