add tf cnn back
d2l-ai/d2l-en pull request #1882
Opened 2021-08-11 23:09 UTC by mli

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2021-08-11 23:11 UTC, terrytangyuan approved these changes
When was this removed earlier?

2021-08-12 05:21 UTC, mli commented
Job d2l-en/PR-1882/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1882/

2021-08-12 06:47 UTC, mli commented
Job d2l-en/PR-1882/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1882/

2021-08-12 09:46 UTC, AnirudhDagar requested changes
@mli I've made some comments. PTAL!

2021-08-12 09:46 UTC, AnirudhDagar commented on chapter_convolutional-modern/alexnet.md
> +:begin_tab:`pytorch`
```suggestion
:begin_tab:`tensorflow`
```

This should be a tensorflow tab.

2021-08-12 09:46 UTC, AnirudhDagar commented on chapter_convolutional-modern/alexnet.md
> +%%tab tensorflow
```suggestion
#@tab tensorflow
```
Why is this not following this syntax? Looks confusing.

2021-08-12 09:46 UTC, AnirudhDagar commented on chapter_convolutional-modern/alexnet.md
> +%%tab tensorflow
Similarly for places below.

2021-08-13 22:32 UTC, mli commented on chapter_convolutional-modern/alexnet.md
> +:begin_tab:`pytorch`
good catch, thanks.

2021-08-13 22:32 UTC, merged