fix adaption typo
d2l-ai/d2l-en pull request #1886
Opened 2021-08-15 17:49 UTC by 315930399

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2021-08-15 17:57 UTC, mli commented
Job d2l-en/PR-1886/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1886/

2021-08-15 18:15 UTC, AnirudhDagar requested changes
@315930399 nice catch! I've made a small comment please make the changes if that sounds better. :))

2021-08-15 18:15 UTC, AnirudhDagar commented on chapter_attention-mechanisms/attention-scoring-functions.md
> +        # Set `keys.transpose(1,2)` to swap the last two dimensions of `keys`
```suggestion
        # Swap the last two dimensions of `keys` with `keys.transpose(1,2)`
```

2021-08-16 01:31 UTC, mli commented
Job d2l-en/PR-1886/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1886/

2021-08-20 03:52 UTC, AnirudhDagar approved these changes
Thanks! LGTM

2021-08-20 03:52 UTC, merged