RL chapter - index and mdp notebooks
d2l-ai/d2l-en pull request #1988
Opened 2021-12-10 23:34 UTC by rasoolfa

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2021-12-11 07:24 UTC, astonzhang commented
Thanks! Can you take a look at the CI error and make the PR pass?

2021-12-11 10:42 UTC, rasoolfa commented
Thanks I reviewed the CI errors. It failed due two reasons: 
1. these notebooks use gym, so it needs to installed ( i.e pip install gym). Not sure how it can be done, should "gym==0.21.0" be added to build.yml? or to setup.py ( this one didn't work).

2. it seems "d2lbook build lib --tab all" doesn't go through to build my python package, although it works just fine locally. Do you know which config file needs to be changed to fix this? do you have any comments about this?

tnx.

2021-12-11 22:30 UTC, astonzhang commented
1. Since gym is probably only needed for the RL chapter, I'd suggest inserting `%pip install gym==0.21.0` right above import statements. In this way, users who don't use RL chapters can save time & local storage from gym installation.
2. You may run `d2lbook build lib` locally - this will change d2l/* files. Then just push changes to these files. The CI will install the d2l lib from source (including your changes): https://github.com/d2l-ai/d2l-en/blob/master/static/build.yml#L5

2021-12-13 11:51 UTC, mli commented
Job d2l-en/PR-1988/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1988/

2021-12-13 11:54 UTC, rasoolfa commented
Thanks @astonzhang. All CL errors are resolved :)

2021-12-13 13:22 UTC, goldmermaid commented
> Thanks @astonzhang. All CL errors are resolved :)

Hey @rasoolfa , the preview link seems not include the RL chapter. To render this chapter, you can simply add `chapter_reinforcement_learning/index` to the [d2l index file](https://github.com/d2l-ai/d2l-en/blob/master/index.md) through this PR.

![image](https://user-images.githubusercontent.com/37914843/145820156-7492b7c1-7e68-4ca9-854b-b8c13a21a0f1.png)

2021-12-13 18:31 UTC, mli commented
Job d2l-en/PR-1988/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1988/

2021-12-13 19:14 UTC, rasoolfa commented
index got update. Let me know if there is anything else needs to be done.

2021-12-16 05:28 UTC, astonzhang requested changes
Thanks! The MDP was explained very clearly. Nice work!

1. Can you take a look at my comments?
2. Can you remove value-iter from this PR? Let's aim at merging mdp only in this PR.
3. Some comments to mdp may apply to value-iter. After merging this PR, can you self-review value-iter before sending another PR on it?

cc @goldmermaid  please take a look at Rasool's revision on mdp. When the PR looks good to you, I'll do another pass. Thanks.

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +Note that if $\gamma$ is very small, the rewards earned by the robot in the far future, say $t = 1000$, are heavily discounted by the factor $\gamma^{1000}$. This encourages the robot to select short
Maybe we should highlight "explore" and "rushing out"

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +We next study the transition function $T(s, a, s') = P(s' \mid s, a)$ in greater detail. Let us think of the state $s_t$ as the location of the robot, as above. And think of the action of the robot a
Let's

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +We next study the transition function $T(s, a, s') = P(s' \mid s, a)$ in greater detail. Let us think of the state $s_t$ as the location of the robot, as above. And think of the action of the robot a
but also -> , and also
(not only, but also)

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +Markov systems are all systems where the next state $s_{t+1}$ is only a function of the current $s_t$ and the action taken at the current state $a_t$; the next state does not depend on which actions
`*Markov systems*` (highlight terms in definitions)

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +Markov systems are all systems where the next state $s_{t+1}$ is only a function of the current $s_t$ and the action taken at the current state $a_t$; the next state does not depend on which actions
the action taken at the current state $a_t$
->
the action taken $a_t$ at the current state

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +Markov systems are all systems where the next state $s_{t+1}$ is only a function of the current $s_t$ and the action taken at the current state $a_t$; the next state does not depend on which actions
"the system above" is not clear: use `:eqlabel:` and `:eqref:`

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +Markov systems are all systems where the next state $s_{t+1}$ is only a function of the current $s_t$ and the action taken at the current state $a_t$; the next state does not depend on which actions
`$(\text{location}, \text{velocity})$`

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +* A MDP is defined by a tuple of four entities $(S, A, T, r)$.
Be self-contained in the summary without undefined notations.

2021-12-16 05:28 UTC, astonzhang commented on chapter_reinforcement_learning/mdp.md
> +* A MDP is defined by a tuple of four entities $(S, A, T, r)$.
We probably can add more bullet points in the summary

2022-01-20 00:14 UTC, rasoolfa commented on chapter_reinforcement_learning/mdp.md
> +A Markov Decision Process (MDP) is a model for how the state of a system evolves as different actions are applied to it. A few different quantities come together to form an MDP as follows.
MDP is very common and that is why used instead of Markov decision process. let me know if the current update is not good with you.

2022-01-20 00:19 UTC, rasoolfa commented on chapter_reinforcement_learning/mdp.md
> +Think of the situation when the robot continues to travel in the gridworld without ever reaching goal location. The sequence of states and actions in a trajectory can be infinitely long in this case
goal is not refered to a goal location, but general goal in RL.

2022-01-20 00:22 UTC, rasoolfa commented
Apologies for delayed updates. I'll do a better job in responding to the comments from now on. Thanks again.

2022-01-20 02:57 UTC, mli commented
Job d2l-en/PR-1988/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1988/

2022-01-20 03:04 UTC, mli commented
Job d2l-en/PR-1988/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1988/

2022-01-20 05:33 UTC, mli commented
Job d2l-en/PR-1988/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1988/

2022-01-20 06:29 UTC, cheungdaven commented on chapter_reinforcement_learning/mdp.md
>  Let us now consider the situation when the robot starts at a particular state $s_0 \in S$ continues taking actions to result in a trajectory
s_0 \in \mathcal{S}

and continues

2022-01-20 06:33 UTC, cheungdaven commented on chapter_reinforcement_learning/mdp.md
> +Think of the situation when the robot continues to travel in the gridworld without ever reaching goal location. The sequence of states and actions in a trajectory can be infinitely long in this case
reaching the goal location

2022-01-20 09:38 UTC, mli commented
Job d2l-en/PR-1988/12 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1988/

2022-01-21 10:25 UTC, mli commented
Job d2l-en/PR-1988/13 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1988/

2022-01-24 19:15 UTC, astonzhang commented on chapter_reinforcement_learning/index.md
> +value-iter
remove value-iter

2022-01-25 00:14 UTC, mli commented
Job d2l-en/PR-1988/14 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1988/

2022-01-25 18:52 UTC, cheungdaven commented
lgtm @astonzhang

2022-01-25 19:07 UTC, merged

2022-01-25 19:35 UTC, rasoolfa commented
yayyy, thanks again for your comments and help.