Fix Typo
d2l-ai/d2l-en pull request #2004
Opened 2022-01-06 13:48 UTC by qingfengtommy

The original interval is written in  [(1.99995,2.00005], which has an additional (.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2022-01-06 13:56 UTC, mli commented
Job d2l-en/PR-2004/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-2004/

2022-01-06 18:02 UTC, AnirudhDagar requested changes
Thanks @qingfengtommy for the fix! I made a small comment, please commit that before we can merge this.

2022-01-06 18:02 UTC, AnirudhDagar commented on chapter_appendix-mathematics-for-deep-learning/random-variables.md
> +Notice that if we know the position accurate to $k=4$ digits after the decimal. that means we know the value falls within the interval say $[1.99995,2.00005]$ which is an interval of length $2.00005-
```suggestion
Notice that if we know the position accurate to $k=4$ digits after the decimal, that means we know the value falls within the interval say $[1.99995,2.00005]$ which is an interval of length $2.00005-1.99995 = 10^{-4}$.  Thus, if we call the length of this interval $\epsilon$, we can say
```

2022-01-07 01:57 UTC, qingfengtommy commented
> Thanks @qingfengtommy for the fix! I made a small comment, please commit that before we can merge this.
You are welcome! Please check again!

2022-01-07 02:00 UTC, mli commented
Job d2l-en/PR-2004/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-2004/

2022-01-07 03:18 UTC, qingfengtommy reviewed
@AnirudhDagar
You are welcome! Please check again!

2022-01-07 21:57 UTC, merged

2022-01-07 21:57 UTC, AnirudhDagar commented
LGTM! Thanks again.

2022-01-08 08:53 UTC, astonzhang commented
@qingfengtommy thanks! Could you send another PR to replace your github ID with your name in our acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md