RL chapter - value-iteration notebook
d2l-ai/d2l-en pull request #2043
Opened 2022-02-12 10:59 UTC by rasoolfa

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2022-02-16 02:17 UTC, cheungdaven requested changes

2022-02-16 02:17 UTC, cheungdaven commented on chapter_reinforcement_learning/value-iter.md
> +    env_desc      = einfo['desc'] # 2D array specifying what each grid item means
This line exceeds the maximum line length 78, you can check the length by enabling the ruler extension. please refer to http://book.d2l.ai/user/code.html for more details.

2022-02-18 09:01 UTC, cheungdaven commented on chapter_reinforcement_learning/value-iter.md
> +$$Q^\pi(s, a) = r(s, a) + \gamma \sum_{s' \in \mathcal{S}} P(s' \mid s, a) \sum_{a' \in \mathcal{A}} \pi(a' \mid s')\ Q^\pi(s', a')\text{ for all } s \in \mathcal{S}, a \in \mathcal{A}.$$:eqlabel:`eq
Sure, feel free to leave the space here, just don’t forget “;”. Thanks.

2022-02-18 09:13 UTC, rasoolfa commented on chapter_reinforcement_learning/value-iter.md
> +$$Q^\pi(s, a) = r(s, a) + \gamma \sum_{s' \in \mathcal{S}} P(s' \mid s, a) \sum_{a' \in \mathcal{A}} \pi(a' \mid s')\ Q^\pi(s', a')\text{ for all } s \in \mathcal{S}, a \in \mathcal{A}.$$:eqlabel:`eq
tnx

2022-02-18 09:54 UTC, rasoolfa commented on chapter_reinforcement_learning/value-iter.md
> +afterall, the optimal action at stage $s$ is the one that maximizes the sum of reward $r(s, a)$ from the first stage and the average return of the trajectories starting from the next stage $s'$, aver
thanks. let me know if this updated version is more clear

2022-02-19 01:23 UTC, cheungdaven approved these changes

2022-03-07 22:32 UTC, AnirudhDagar commented
@d2l-bot please rebuild!

2022-03-17 20:19 UTC, astonzhang commented
Hi @rasoolfa  Thanks! Could you move this PR to the https://github.com/d2l-ai/d2l-en/tree/vol2-rl branch? We'll go from there soon!

2022-11-20 00:28 UTC, astonzhang commented
Closing this PR per offline discussions that new PRs will be posted on d2l-ai:vol2-rl branch

2022-11-20 00:28 UTC, closed without merging