TF `try_gpu` string output fix
d2l-ai/d2l-en pull request #2062
Opened 2022-03-11 13:19 UTC by biswajitsahoo1111

*Description of changes:*

This pull request only affects the string output that is generated after training `seq2seq` model. For example, the following old output
```
x tokens/sec on <tensorflow.python.eager.context._EagerDeviceContext object at 0x7ff8005deb00>
```
becomes
```
x tokens/sec on /GPU:0
```

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

2022-03-14 23:41 UTC, AnirudhDagar requested changes
This works and definitely shows a much better output for device name, but I'm not sure using a private attribute is the best thing to do here. I don't think there is any other way in TF to achieve this. Thoughts @astonzhang?

@biswajitsahoo1111 thanks for your contribution, I've made some comments, please address those. You will need the d2lbook package generally for d2l development. Feel free to refer to CONTRIBUTING.md for more info :))

2022-03-14 23:41 UTC, AnirudhDagar commented on d2l/tensorflow.py
> +import numpy as np
Please revert these changes.

2022-03-14 23:41 UTC, AnirudhDagar commented on d2l/tensorflow.py
> -import numpy as np
Please revert these changes.

2022-03-14 23:41 UTC, AnirudhDagar commented on d2l/tensorflow.py
> +
Please remove this addition of blank line.

2022-03-14 23:41 UTC, AnirudhDagar commented on d2l/tensorflow.py
>  def use_svg_display():
Please revert these changes.

2022-03-14 23:41 UTC, AnirudhDagar commented on d2l/tensorflow.py
> +          f'tokens/sec on {str(device._device_name)}')
Please make the same change in https://github.com/d2l-ai/d2l-en/blob/master/chapter_appendix-tools-for-deep-learning/utils.md and then run d2lbook build lib. We don't directly change the lib files, these are automatically generated using the d2lbook package after editing the source files where these functions are saved.

2022-03-15 09:57 UTC, biswajitsahoo1111 commented
running `d2lbook build lib` has significantly changed all files in `d2l` folder. Don't know why. Looking into it.

2022-03-15 10:00 UTC, AnirudhDagar commented
Can you please make sure you have the most recent version of d2lbook and you run it after rebasing your branch with the latest changes in master?

`pip install --upgrade git+https://github.com/d2l-ai/d2l-book`

2022-03-15 16:19 UTC, merged