Wrong statement regarding weight decay in pytorch
d2l-ai/d2l-en pull request #2284
Opened 2022-08-30 15:27 UTC by finale80

The two sentences 
*[...] By default, PyTorch decays both weights and biases simultaneously. Here, we only set weight_decay for the weight, so the bias parameter b will not decay [...]*
contradict each other. More specifically, I believe the 2nd one is wrong.

As from PyTorch implementation https://github.com/pytorch/pytorch/blob/acd6ca8cfa9537284928fb5d36834d1e5ae1e6f3/torch/optim/sgd.py#L120
all parameters receive the same weight decay.
So the first sentence is correct.

In the example of this chapter, to avoid decaying the bias, one would need to use the following
```
...
   def loss(self, y_hat, y):
        return super().loss(y_hat, y) + self.weight_decay * 0.5 * (self.net.weight**2).sum()

    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=self.lr, weight_decay=0)
...
```

I attach here a self-contained example based on this chapter
(note: I used .txt to bypass file extension checking).

The code compares 3 versions of the model
1. the default implementation (i.e., the one suggested by the book which decays all parameters)
2. a "manual" implementation of the default behaviour (to show that the default is indeed decaying all parameters)
3. the option mentioned above (which does not decay the bias).

Overall, the simplest way to fix the problem is to drop the 2nd sentence as proposed.

Alternatively, one could add the comparison as from the code attached. But
1. I need to be extended to Tensorflow and MXNet
6. I think the right way to skip the decay would be by specifying the parameter differently (I believe one could group parameters with different options). But this would be too much details given the aim of the chapter

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

[chapter3.7_weight-decay.py.txt](https://github.com/d2l-ai/d2l-en/files/9454152/chapter3.7_weight-decay.py.txt)

2022-08-31 18:23 UTC, AnirudhDagar reviewed
Thanks @finale80 for your PR!

This is a good catch and makes sense now. I remember adding this statement earlier because it was actually relevant at the time of writing the code for pytorch version (see #912) in the old d2l api. We used to only decay the weight params and not the bias.

So we had something like the following to handle weight decay separately for pytorch:

```python
      return torch.optim.SGD([
          {"params":self.net.weight,'weight_decay': self.wd},
          {"params":self.net.bias}], lr=self.lr)
```

I see that the above code was refactored and changed in #2034 and the text related to the code change was probably missed.

@cheungdaven after PR #2034 there seems to be an inconsistency between pytorch and mxnet. Specifically mxnet doesn't decay bias but pytorch does. I'm curious if there was any specific reason to remove [these L394-396](https://github.com/d2l-ai/d2l-en/pull/2034/files#diff-8be31f544cfaa6008c11c863dba743c9a4abb4a0436abb2763810b701d41fed0L394-L396)?

2022-09-09 00:22 UTC, cheungdaven commented
It makes sense to me. feel free to change it back @AnirudhDagar

2022-09-09 02:30 UTC, AnirudhDagar commented
Thanks @cheungdaven! @finale80 could you please add the params grouping back in pytorch code like we had before instead of editing the text?

2022-09-10 10:50 UTC, finale80 commented
@AnirudhDagar done!

More specifically
* I've updated the code
* I re-integrated the original statement in the text (removed in my PR) and added minor modification to the text (to make it even more clear).

I also double checked the code and indeed everything is consistent now.
I attach my updated script.](url)
[chapter3.7_weight-decay.py.txt](https://github.com/d2l-ai/d2l-en/files/9540129/chapter3.7_weight-decay.py.txt)

2022-09-10 11:26 UTC, AnirudhDagar requested changes
@finale80 just a minor style comment below (the idea is to minimize usage of lines wherever possible), the rest looks good. Thanks, will merge this after the change.

2022-09-10 11:26 UTC, AnirudhDagar commented on chapter_linear-regression/weight-decay.md
> +        )
```suggestion
        return torch.optim.SGD([
            {'params': self.net.weight, 'weight_decay': self.wd},
            {'params': self.net.bias}], lr=self.lr)
```

2022-09-10 20:01 UTC, AnirudhDagar commented on chapter_linear-regression/weight-decay.md
> +        """Defined in :numref:`sec_linear_concise`"""
Also no need to add this line.
```suggestion
```

2022-09-10 20:02 UTC, AnirudhDagar approved these changes

2022-09-10 21:05 UTC, merged